#!/bin/bash
#
# Created by argbash-init v2.8.0
# DEFINE_SCRIPT_DIR([])
# INCLUDE_PARSING_CODE([_parsing.sh])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.8.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info

# OTHER STUFF GENERATED BY Argbash
script_dir="$(cd "$(dirname "$(readlink -e "${BASH_SOURCE[0]}")")" && pwd)" || die "Couldn't determine the script's running directory, which probably matters, bailing out" 2
. "$script_dir/_parsing.sh"  # '.' means 'source'


### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash



# printf "Value of '%s': %s\\n" 'command' "$_arg_command"

. "$script_dir/_run.sh"

# ] <-- needed because of Argbash
