#!/bin/bash

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

VENV_DIR=${DIR}/venv

type python3 >/dev/null 2>&1 || sudo zypper install --no-confirm python3

if [ ! -d $VENV_DIR ]; then
  python3 -m venv $VENV_DIR
fi

$VENV_DIR/bin/pip3 install requests pygal
$VENV_DIR/bin/python3 $(dirname $0)/capture.py $@
