---

- hosts: osh-deployer
  gather_facts: yes
  any_errors_fatal: true
  pre_tasks:
    #http://jinja.pocoo.org/docs/2.10/templates/#default
    - name: Check if developer mode should be enabled
      set_fact:
        developer_mode: "{{ (lookup('env','OSH_DEVELOPER_MODE') | default('False', true) ) | bool }}"
      tags:
        - always
        - imagebuilder
        - upstream_patching
  roles:
    - role: dev-patcher
      when: developer_mode
      tags:
        - upstream_patching

- hosts: osh-deployer
  gather_facts: no
  any_errors_fatal: true
  roles:
    - role: suse-build-images
      tags:
        - imagebuilder
      when:
        - developer_mode
        - build_osh_images | default('False') | bool

- hosts: osh-deploy-cp:caasp-workers
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: setup-caasp-workers
      tags:
        - workersetup

- hosts: osh-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: suse-osh-deploy
      tags:
        - deploy
