---

- hosts: osh-deployer
  gather_facts: yes
  any_errors_fatal: true
  pre_tasks:
    #http://jinja.pocoo.org/docs/2.10/templates/#default
    - name: Check if developer mode should be enabled
      set_fact:
        developer_mode: "{{ (lookup('env','OSH_DEVELOPER_MODE') | default('False', true) ) | bool }}"
  roles:
    - role: suse-dev-patcher
      when: developer_mode

- hosts: osh-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - role: suse-build-images
      when:
        - developer_mode
        - build_osh_images | default('False') | bool

- hosts: osh-deploy-cp
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - suse-osh-setup

- hosts: osh-deployer
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - suse-osh-deploy
